import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronRight,ClipboardList,Copy,Database,FileText,FolderOpen,Layers3,LoaderCircle,MessageSquare,Network,Pencil,Search,Send,ShieldCheck,SlidersHorizontal,Upload,X} from 'lucide-react';
import {stages,taskBrief,type WorkItem} from './workflow';
import type {Task,TaskState,Resource} from './types';
import taskData from './tasks.json';
import resourceData from './resources.json';
import ContentWorkspace from './ContentWorkspace';
const tasks=taskData as Task[];
const resources=resourceData as Resource[];
const moduleNames:Record<string,string>={shared:'共用支撑',...Object.fromEntries(stages.map(s=>[s.id,s.title]))};
const moduleIcons={research:Search,creation:Pencil,review:ShieldCheck,publishing:Send,feedback:MessageSquare};
const operationStatuses=['待开始','进行中','待验收','已完成'] as const;
const moduleStatuses=['待补充','待试跑','进行中','已跑通'] as const;
const fmt=(text:string)=>text||'尚未填写';
function Source({url,children}:{url?:string;children:ReactNode}){return url&&/^https?:\/\//.test(url)?<a href={url} target='_blank' rel='noreferrer'>{children}<ArrowUpRight size={14}/></a>:<span>{children}</span>;}
function Lines({text}:{text:string}){return <p className='multiline'>{text}</p>;}
function Field({title,children}:{title:string;children:ReactNode}){return <section className='detail-field'><h3>{title}</h3>{children}</section>;}
function Modal({title,subtitle,children,onClose,busy=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;busy?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current!;d.showModal();return()=>d.close();},[]);return <dialog ref={ref} className='modal' onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className='modal-head'><div><span className='eyebrow'>WORKBENCH / DETAIL</span><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className='icon-btn' aria-label='关闭详情' disabled={busy} onClick={onClose}><X/></button></div>{children}</dialog>;}
function saveFile(name:string,content:string,type='text/markdown;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function taskText(t:Task,s:TaskState|undefined,states:TaskState[]){return `# ${t.id} · ${t.title}\n\n模块：${moduleNames[t.module]} / ${t.part}\n负责人：${s?.owner||'待分配'}\n状态：${s?.status||'待开始'}\n优先级：${t.priority}\n\n## 上游依赖\n${t.dependsOn.map(id=>{const upstream=states.find(x=>x.id===id);return `- ${id} ${tasks.find(x=>x.id===id)?.title||''}：${upstream?.resultUrl||'待提供成果或材料'}`;}).join('\n')||'无'}\n\n## 输入\n${t.input}\n\n## 步骤\n${t.steps.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n## 交付\n${t.output}\n\n## 验收\n${t.acceptance}\n\n## 复用\n${t.reuse.map(r=>`- 什么：${r.name}\n- 怎么用：${r.how}\n- 为什么：${r.why}\n- 来源：${r.url||'本地能力，见使用说明'}`).join('\n')}\n\n## 执行记录\n${s?.notes||'待补充'}\n\n成果链接：${s?.resultUrl||'待补充'}\n\n外部账号操作按任务授权与平台规则执行；本工作台未连接任何社媒发布账号。`;}
export default function App(){
 const [view,setView]=useState('content'),[items,setItems]=useState<WorkItem[]>([]),[states,setStates]=useState<TaskState[]>([]),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true),[active,setActive]=useState('research');
 const [moduleDraft,setModuleDraft]=useState<WorkItem|null>(null),[taskDraft,setTaskDraft]=useState<TaskState|null>(null),[resource,setResource]=useState<Resource|null>(null),[busy,setBusy]=useState(false),[editError,setEditError]=useState(''),[notice,setNotice]=useState('');
 const [query,setQuery]=useState(''),[moduleFilter,setModuleFilter]=useState('all'),[statusFilter,setStatusFilter]=useState('all'),[kindFilter,setKindFilter]=useState('all'),[researchMode,setResearchMode]=useState('library'),[restore,setRestore]=useState<any>(null);
 const [discard,setDiscard]=useState<'modules'|'tasks'|null>(null);
 const [contentDirty,setContentDirty]=useState(false),[contentEpoch,setContentEpoch]=useState(0);
 const fileRef=useRef<HTMLInputElement>(null);
 async function refresh(){setLoading(true);try{const responses=await Promise.all([fetch('/api/modules',{cache:'no-store'}),fetch('/api/tasks',{cache:'no-store'})]);const values=await Promise.all(responses.map(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error||'无法读取本地数据');return v;}));setItems(values[0].items);setStates(values[1].items);setLoadError('');}catch(e){setLoadError(e instanceof Error?e.message:'无法连接本地服务。请重新启动工作台。');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
 function navigate(next:string){if(next===view)return;if(contentDirty){if(!window.confirm('内容修改尚未保存。放弃修改并离开？'))return;setContentDirty(false);setContentEpoch(n=>n+1);}setView(next);setQuery('');setModuleFilter('all');setStatusFilter('all');}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('任务已复制，可交给其他人或 agent。');}catch{saveFile('任务交接.md',text);setNotice('复制不可用，已下载任务文件。');}}
 async function save(kind:'modules'|'tasks'){const body=kind==='modules'?moduleDraft:taskDraft;setBusy(true);setEditError('');try{const response=await fetch('/api/'+kind,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'保存失败');if(kind==='modules'){setItems(prev=>prev.map(x=>x.id===data.item.id?data.item:x));setModuleDraft(null);}else{setStates(prev=>prev.map(x=>x.id===data.item.id?data.item:x));setTaskDraft(null);}setDiscard(null);setNotice('已保存到本机。');}catch(e){setEditError(e instanceof Error?e.message:'保存失败，输入仍保留。');}finally{setBusy(false);}}
 function exportAll(){saveFile('全部工作-交接包.md','# 内容工作台 · 全部工作交接包\n\n导出时间：'+new Date().toISOString()+'\n\n'+tasks.map(t=>taskText(t,states.find(s=>s.id===t.id),states)).join('\n\n---\n\n'));setNotice('已导出全部任务、当前负责人和执行记录。');}
 function closeModule(){if(!moduleDraft)return;const dirty=JSON.stringify(moduleDraft)!==JSON.stringify(items.find(x=>x.id===moduleDraft.id));if(dirty)setDiscard('modules');else setModuleDraft(null);}
 function closeTask(){if(!taskDraft)return;const dirty=JSON.stringify(taskDraft)!==JSON.stringify(states.find(x=>x.id===taskDraft.id));if(dirty)setDiscard('tasks');else setTaskDraft(null);}
 async function recoverDraft(kind:'modules'|'tasks'){const current=kind==='modules'?moduleDraft:taskDraft;if(!current)return;const text=kind==='modules'?taskBrief(moduleDraft!,items):taskText(tasks.find(t=>t.id===taskDraft!.id)!,taskDraft!,states);saveFile('未保存草稿-'+current.id+'.md',text);setBusy(true);try{const response=await fetch('/api/'+kind,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'读取失败');if(kind==='modules'){setItems(data.items);setModuleDraft(structuredClone(data.items.find((i:WorkItem)=>i.id===current.id)));}else{setStates(data.items);setTaskDraft(structuredClone(data.items.find((i:TaskState)=>i.id===current.id)));}setEditError('');setNotice('原草稿已下载，编辑器已载入最新记录，请合并后保存。');}catch(e){setEditError(e instanceof Error?e.message:'读取失败，原输入仍保留。');}finally{setBusy(false);}}
 async function chooseRestore(file?:File){if(!file)return;try{if(file.size>16*1024*1024)throw new Error('备份超过 16 MB，请核对文件。');const data=JSON.parse(await file.text());if(data.app!=='content-workbench-local'||data.version!==1||!Array.isArray(data.modules)||!Array.isArray(data.tasks))throw new Error('这不是本工作台的版本 1 备份。');setEditError('');setRestore(data);}catch(e){setNotice(e instanceof Error?e.message:'备份无法读取');}if(fileRef.current)fileRef.current.value='';}
 async function doRestore(){setBusy(true);setEditError('');try{const r=await fetch('/api/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(restore)});const v=await r.json();if(!r.ok)throw new Error(v.error||'恢复失败');setRestore(null);setContentDirty(false);setContentEpoch(n=>n+1);await refresh();setNotice('备份已恢复，恢复前的数据已另存快照。');}catch(e){setEditError(e instanceof Error?e.message:'恢复失败');}finally{setBusy(false);}}
 const selected=items.find(x=>x.id===active),stage=stages.find(s=>s.id===active)!;
 const filteredTasks=tasks.filter(t=>(moduleFilter==='all'||t.module===moduleFilter)&&(statusFilter==='all'||states.find(s=>s.id===t.id)?.status===statusFilter)&&(t.title+t.part+t.reuse.map(r=>r.name+r.how+r.why).join('')).toLowerCase().includes(query.toLowerCase()));
 const filteredResources=resources.filter(r=>(moduleFilter==='all'||r.stages.includes(moduleFilter))&&(kindFilter==='all'||r.kind===kindFilter)&&(r.name+r.summary+r.reuse).toLowerCase().includes(query.toLowerCase()));
 const editedTask=taskDraft?tasks.find(t=>t.id===taskDraft.id):undefined;
 return <div className='app'><header className='topbar'><a className='brand' href='/'><span className='brand-symbol'><Layers3 size={25}/></span><span>Launch Loop <small>内容工作台</small></span></a><span className='local-label'><span/>本地运行 · 无需登录</span><div className='top-actions'><a href='/api/backup' download='内容工作台备份.json' className='button subtle'><Database size={16}/>备份数据</a><button className='button subtle' onClick={()=>fileRef.current?.click()}><Upload size={16}/>恢复备份</button><input ref={fileRef} type='file' accept='.json,application/json' hidden onChange={e=>void chooseRestore(e.target.files?.[0])}/></div></header>
 <div className='layout'><aside className='sidebar'><div className='sidebar-label'>工作空间</div><nav>{[{id:'content',label:'内容作品',icon:FileText},{id:'workflow',label:'五步工作流',icon:Layers3},{id:'tasks',label:'全部工作与分工',icon:ClipboardList},{id:'research',label:'竞品与复用库',icon:BookOpen},{id:'architecture',label:'架构与取舍',icon:Network},{id:'guide',label:'使用与交接',icon:FolderOpen}].map(n=><button key={n.id} onClick={()=>navigate(n.id)} aria-current={view===n.id?'page':undefined}><n.icon size={19}/>{n.label}{view===n.id&&<ChevronRight size={15}/>}</button>)}</nav><div className='sidebar-bottom'><span className='eyebrow'>当前示例项目</span><Source url='https://github.com/ThinkFlowLab/system1-agents'>system1-agents</Source><p>先完成一条真实内容，再把重复步骤交给 agent。</p><span className='subtle-text'>调研核查 · 2026.09.23</span></div></aside>
 <main>{notice&&<div role='status' className='toast'><Check size={18}/>{notice}</div>}{loadError&&<div className='error-banner' role='alert'>{loadError}<button className='button' onClick={()=>void refresh()}>重新读取</button></div>}
 {view==='content'&&<ContentWorkspace key={contentEpoch} reloadToken={contentEpoch} onDirtyChange={setContentDirty}/>}
 {view==='workflow'&&<><div className='page-heading'><div><span className='eyebrow'>WORKSPACE / 01</span><h1>五步，做好一次内容工作。</h1><p>把研究变成内容，把反馈带回下一轮。每个模块都有操作说明和交接入口。</p></div><button className='button' disabled={loading||!!loadError} onClick={exportAll}><ArrowDownToLine size={17}/>导出交接包</button></div><div className='stats-strip'><span><strong>{tasks.length}</strong> 项具体工作</span><span><strong>{states.filter(x=>x.status==='已完成').length}</strong> 项已完成</span><span><strong>{resources.length}</strong> 项复用资源</span><span className='strip-note'>账号未连接 · 发布由执行者操作</span></div>
 <div className='stage-grid'>{stages.map(s=>{const Icon=moduleIcons[s.id];return <button key={s.id} className={'stage-card '+(active===s.id?'active':'')} style={{'--stage':s.color} as React.CSSProperties} onClick={()=>setActive(s.id)}><div><Icon size={22}/><span>{s.number}</span></div><h2>{s.title}</h2><p>{s.description}</p><footer><span>{items.find(x=>x.id===s.id)?.status||'读取中'}</span><ArrowRight size={17}/></footer></button>;})}</div>
 {selected?<div className='module-layout'><article className='panel module-panel'><div className='panel-heading'><div><span className='eyebrow'>{stage.english}</span><h2>{stage.title}模块</h2></div><button className='button' disabled={!!loadError} onClick={()=>{setEditError('');setModuleDraft(structuredClone(selected));}}><Pencil size={16}/>补充模块</button></div><Field title='准备什么'><div className='input-box'><Lines text={selected.input}/></div></Field><Field title='怎么做'><ol className='steps'>{selected.steps.map((step,i)=><li key={i}><span>{i+1}</span><p>{step}</p></li>)}</ol></Field><div className='two-col'><Field title='交付什么'><Lines text={selected.output}/></Field><Field title='做到什么算完成'><Lines text={selected.acceptance}/></Field></div><Field title='优先复用'><Lines text={selected.tools}/></Field><Field title='执行记录'><Lines text={fmt(selected.notes)}/></Field></article><aside className='module-side'><section className='panel'><h3>交给谁来做</h3><dl><dt>负责人</dt><dd>{selected.owner||'待分配'}</dd><dt>当前状态</dt><dd>{selected.status}</dd><dt>交给下一步</dt><dd>{stage.handoff}</dd></dl>{selected.resultUrl?<Source url={selected.resultUrl}>查看模块成果</Source>:<p className='muted'>完成后，补充成果链接。</p>}<button className='button full primary' onClick={()=>void copy(taskBrief(selected,items))}><Copy size={16}/>复制模块任务</button></section><section className='panel'><h3>这个模块的具体工作</h3><div className='mini-task-list'>{tasks.filter(t=>t.module===active).map(t=><button key={t.id} disabled={loading||!!loadError} onClick={()=>{setEditError('');setTaskDraft(structuredClone(states.find(s=>s.id===t.id)!));}}><span>{t.part}</span><ChevronRight size={14}/></button>)}</div><button className='text-btn' onClick={()=>{navigate('tasks');setModuleFilter(active);}}>看输入、复用和验收 <ArrowRight size={15}/></button></section></aside></div>:<div className='panel loading'><LoaderCircle/>正在读取本地工作台…</div>}</>}
 {view==='tasks'&&<><div className='page-heading'><div><span className='eyebrow'>TASKS / 02</span><h1>每一项工作，都可以交接。</h1><p>五个业务模块 + 共用支撑。点开任务，查看输入、步骤、复用理由和验收条件。</p></div><button className='button' disabled={loading||!!loadError} onClick={exportAll}><ArrowDownToLine size={17}/>导出全部任务</button></div><div className='filterbar'><label className='search'><Search size={18}/><input aria-label='搜索任务' placeholder='搜索工作、部分或复用工具' value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label='筛选任务模块' value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value='all'>全部模块</option>{Object.entries(moduleNames).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select><select aria-label='筛选任务状态' value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value='all'>全部状态</option>{operationStatuses.map(s=><option key={s}>{s}</option>)}</select><span>{filteredTasks.length} 项</span></div><div className='task-table panel'><table><thead><tr><th>工作 / 交付物</th><th>模块</th><th>优先复用与理由</th><th>负责人 / 状态</th><th/></tr></thead><tbody>{filteredTasks.map(t=>{const state=states.find(s=>s.id===t.id);return <tr key={t.id}><td><small className='task-id'>{t.id.toUpperCase()} · {t.part} · {t.priority}</small><strong>{t.title}</strong><p>{t.output}</p></td><td><span className='tag'>{moduleNames[t.module]}</span></td><td><strong className='reuse-name'>{t.reuse[0].name}</strong><p>{t.reuse[0].why}</p></td><td><span>{state?.owner||'待分配'}</span><span className={'status '+(state?.status==='已完成'?'done':'')}>{state?.status||'待开始'}</span></td><td><button className='button small-btn' disabled={!state||!!loadError} onClick={()=>{setEditError('');setTaskDraft(structuredClone(state!));}}>查看 / 更新</button></td></tr>;})}</tbody></table>{!filteredTasks.length&&<div className='empty'>没有符合筛选条件的任务。</div>}</div><p className='footnote'>“已完成”由执行者按验收条件记录；调研已经写入页面，不会自动把实际运营任务标为完成。</p></>}
 {view==='research'&&<><div className='page-heading'><div><span className='eyebrow'>RESEARCH / 03</span><h1>先复用，再决定要开发什么。</h1><p>覆盖品牌管理、内容营销产品、发布服务、编排工具和 skills；按五步流程比较。</p></div><a className='button' href='/docs/research.md' download><ArrowDownToLine size={17}/>下载完整调研</a></div><div className='notice'><BookOpen size={19}/><p><strong>按笔记中的品牌管理语境，这里核查 Frontify。</strong>Frontity 是另一款 WordPress / React 框架。以下供应商能力来自官方文档核查，未登录商业产品实测；技能样例另有执行记录。</p></div><div className='segmented'><button className={researchMode==='library'?'selected':''} onClick={()=>setResearchMode('library')}>资源与复用说明</button><button className={researchMode==='matrix'?'selected':''} onClick={()=>setResearchMode('matrix')}>产品五步对照</button></div><div className='filterbar'><label className='search'><Search size={18}/><input aria-label='搜索复用资源' placeholder='搜索 Frontify、发布、品牌、MCP…' value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label='筛选资源阶段' value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value='all'>全部阶段</option>{stages.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><select aria-label='筛选资源类型' value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value='all'>全部类型</option><option>Skill</option><option>产品</option><option>现有能力</option></select></div>
 {researchMode==='library'?<div className='resource-grid'>{filteredResources.map(r=><button className='resource-card' key={r.id} onClick={()=>setResource(r)}><div className='resource-top'><span className='tag'>{r.category||r.kind}</span><ArrowUpRight size={18}/></div><h2>{r.name}</h2><p>{r.summary}</p><div className='resource-reuse'><small>值得复用</small><span>{r.reuse}</span></div><footer>{r.stages.map(s=>moduleNames[s]).join(' / ')}</footer></button>)}</div>:<div className='panel matrix'><table><thead><tr><th>产品 / 定位</th>{stages.map(s=><th key={s.id}>{s.title}</th>)}</tr></thead><tbody>{filteredResources.filter(r=>r.kind==='产品').map(r=><tr key={r.id}><th><button className='text-btn' onClick={()=>setResource(r)}>{r.name}<ArrowUpRight size={13}/></button><small>{r.category||'部分功能产品'}</small></th>{stages.map(s=><td key={s.id}>{r.coverage?.[s.id]||'未核实原生能力；不推断支持'}</td>)}</tr>)}</tbody></table></div>}{!filteredResources.length&&<div className='empty'>没有找到资源，试试更短的关键词。</div>}<p className='footnote'>“文档支持”不代表已连通你的账号。试用时先验证输入、输出和限制，再决定购买或接入；费用按官方当前套餐确认。</p></>}
 {view==='architecture'&&<><div className='page-heading'><div><span className='eyebrow'>ARCHITECTURE / 04</span><h1>页面管交接，工具做擅长的事。</h1><p>先由人把五步跑通；模块方法可以并行完善，实际内容按依赖交接。</p></div></div><section className='panel'><div className='context-bar'><FileText size={20}/><strong>共用产品与品牌资料</strong><span>事实 · 术语 · 素材 · 语气 · 来源</span></div><div className='flow-chain'>{stages.map(s=><button key={s.id} onClick={()=>{navigate('workflow');setActive(s.id);}}><span>{s.number}</span><strong>{s.title}</strong><small>{s.handoff}</small></button>)}</div><p className='feedback-arrow'>反馈中的问题和证据，回到下一轮研究 ↩</p></section><div className='decision-grid'><section className='panel'><span className='decision-dot green'/><h2>直接复用</h2><p>skills 的研究与写作方法；发布工具的账号授权、草稿、审批、排期；GitHub 的 Issues；现成统计和数据导出。</p></section><section className='panel'><span className='decision-dot blue'/><h2>本地工作台负责</h2><p>中英文内容、段落编辑、意见与来源、历史版本及批准，以及模块说明、任务分工和备份。所有账号操作由执行者或已接入工具完成。</p></section><section className='panel'><span className='decision-dot amber'/><h2>有证据再增加</h2><p>自动触发、跨工具同步、重试和提醒。连续重复且规则稳定后，从 n8n、Gumloop、Relevance AI 中选一个。</p></section></div><section className='panel'><h2>可以并行交给五位执行者</h2><div className='parallel-list'>{stages.map(s=><div key={s.id}><strong>{s.title}</strong><p>{items.find(x=>x.id===s.id)?.acceptance||s.description}</p><button className='button small-btn' disabled={!items.length} onClick={()=>void copy(taskBrief(items.find(x=>x.id===s.id)!,items))}><Copy size={15}/>复制工作包</button></div>)}</div></section><p className='footnote'>本地版适合同一台电脑维护总台账。其他人通过任务包和成果文件交接；它不提供多台电脑实时同步。</p></>}
 {view==='guide'&&<><div className='page-heading'><div><span className='eyebrow'>START HERE / 05</span><h1>给下一位执行者的使用说明。</h1><p>从一份内容作品开始，编辑、审查并保存版本；方法和分工仍在任务库中。</p></div></div><div className='guide-grid'><section className='panel'><h2>开始工作</h2><ol className='plain-list'><li>双击文件夹里的“启动工作台.cmd”。浏览器会自动打开。</li><li>在“内容作品”新建项目，填写中文、英文文章及各自的 LinkedIn 动态稿。</li><li>按段编辑正文，补充来源和意见，保存新版本；方法和分工可到任务库查看。</li><li>核对四份稿件并处理意见，批准当前版本后导出发布文案 Markdown。改稿后需重新批准。</li><li>点击“备份数据”保留副本；工作结束可双击“停止工作台.cmd”。</li></ol></section><section className='panel'><h2>这次已经补了什么</h2><ul className='plain-list'><li>中英文段落编辑、意见与来源、版本历史和按版本批准；Markdown 工作版／发布版导出。</li><li>Frontify / Frontity 名称核准，品牌工具与营销产品竞争对照。</li><li>{tasks.length} 项具体工作及其复用对象、用法、理由和验收。</li><li>基于 system1-agents 的资料与文案流程样例。</li></ul><p className='muted'>外部产品仅核查官方资料；没有代你购买、开通账号或发布内容。</p></section><section className='panel'><h2>资料与样例</h2><div className='doc-list'><a href='/docs/research.md' download><BookOpen/>完整竞品与复用调研<ArrowDownToLine/></a><a href='/docs/tasks.md' download><ClipboardList/>全部工作与复用清单<ArrowDownToLine/></a><a href='/docs/sample.md' download><FileText/>system1-agents 流程试跑样例<ArrowDownToLine/></a><a href='/docs/guide.md' download><FolderOpen/>本地运行与交接指南<ArrowDownToLine/></a></div></section><section className='panel'><h2>数据和边界</h2><p>内容项目、全部历史版本与批准记录，以及模块和任务保存在本机 data 文件夹；JSON 备份用于换电脑或恢复。素材文件需另行备份，成果链接不包含文件本体。</p><p>查看资料和编辑台账无需联网；打开外部来源、使用在线模型及发布工具需要网络，并受各服务规则与费用限制。</p><p className='muted'>本地界面只监听本机地址；不要把它直接暴露到公网。</p></section></div></>}
 <footer className='footer'><span>内容工作台 · 本地版</span><span>数据留在本机 · 先复用，后自动化</span></footer></main></div>
 {moduleDraft&&<Modal title={'补充'+moduleNames[moduleDraft.id]+'模块'} subtitle='将方法、输入和结果写清楚，让下一位执行者能接手。' busy={busy} onClose={closeModule}>{discard==='modules'&&<div className='discard-prompt' role='alert'><p>模块修改尚未保存，是否放弃？</p><button className='button' onClick={()=>setDiscard(null)}>继续编辑</button><button className='button' onClick={()=>{setDiscard(null);setModuleDraft(null);}}>放弃修改</button></div>}<form onSubmit={e=>{e.preventDefault();void save('modules');}}><fieldset disabled={busy}><div className='two-col'><label>负责人<input value={moduleDraft.owner} maxLength={120} onChange={e=>setModuleDraft({...moduleDraft,owner:e.target.value})}/></label><label>模块状态<select value={moduleDraft.status} onChange={e=>setModuleDraft({...moduleDraft,status:e.target.value as WorkItem['status']})}>{moduleStatuses.map(s=><option key={s}>{s}</option>)}</select></label></div>{([{field:'input',label:'准备的输入'},{field:'tools',label:'优先复用'},{field:'output',label:'交付物'},{field:'acceptance',label:'验收条件'},{field:'notes',label:'执行记录'}] as const).map(f=><label key={f.field}>{f.label}<textarea rows={3} value={moduleDraft[f.field]} onChange={e=>setModuleDraft({...moduleDraft,[f.field]:e.target.value})}/></label>)}<label>操作步骤（每行一步）<textarea rows={5} value={moduleDraft.steps.join('\n')} onChange={e=>setModuleDraft({...moduleDraft,steps:e.target.value.split('\n')})}/></label><label>成果链接<input type='url' placeholder='https://…' value={moduleDraft.resultUrl} onChange={e=>setModuleDraft({...moduleDraft,resultUrl:e.target.value})}/></label>{editError&&<div className='form-error' role='alert'><p>{editError}</p><button type='button' className='button' onClick={()=>void recoverDraft('modules')}>下载当前草稿并载入最新版本</button></div>}<div className='form-actions'><button type='button' className='button' onClick={()=>void copy(taskBrief(moduleDraft,items))}><Copy size={16}/>复制当前内容</button><button className='button primary' type='submit'>{busy?'保存中…':'保存模块'}</button></div></fieldset></form></Modal>}
 {taskDraft&&editedTask&&<Modal title={editedTask.id.toUpperCase()+' · '+editedTask.title} subtitle={moduleNames[editedTask.module]+' / '+editedTask.part+' · '+editedTask.priority} busy={busy} onClose={closeTask}>{discard==='tasks'&&<div className='discard-prompt' role='alert'><p>任务修改尚未保存，是否放弃？</p><button className='button' onClick={()=>setDiscard(null)}>继续编辑</button><button className='button' onClick={()=>{setDiscard(null);setTaskDraft(null);}}>放弃修改</button></div>}<div className='modal-body'><Field title='准备什么'><Lines text={editedTask.input}/></Field><Field title='操作步骤'><ol className='plain-list'>{editedTask.steps.map((s,i)=><li key={i}>{s}</li>)}</ol></Field><div className='two-col'><Field title='交付什么'><Lines text={editedTask.output}/></Field><Field title='怎么验收'><Lines text={editedTask.acceptance}/></Field></div><div className='reuse-box'>{editedTask.reuse.map((r,i)=><div key={i}><h3>复用什么</h3><Source url={r.url}>{r.name}</Source><h3>如何复用</h3><p>{r.how}</p><h3>为什么值得</h3><p>{r.why}</p></div>)}</div><Field title='上游依赖'>{editedTask.dependsOn.length?editedTask.dependsOn.map(id=>{const state=states.find(s=>s.id===id);return <p key={id}>{id.toUpperCase()} · {tasks.find(t=>t.id===id)?.title} — {state?.resultUrl?<Source url={state.resultUrl}>查看成果</Source>:'尚未提供成果链接'}</p>;}):<p>可独立开始。</p>}</Field><form className='task-editor' onSubmit={e=>{e.preventDefault();void save('tasks');}}><fieldset disabled={busy}><h3>执行与分工</h3><div className='two-col'><label>任务负责人<input value={taskDraft.owner} maxLength={120} onChange={e=>setTaskDraft({...taskDraft,owner:e.target.value})}/></label><label>任务状态<select value={taskDraft.status} onChange={e=>setTaskDraft({...taskDraft,status:e.target.value as TaskState['status']})}>{operationStatuses.map(s=><option key={s}>{s}</option>)}</select></label></div><label>执行记录 / 待解决问题<textarea rows={4} value={taskDraft.notes} onChange={e=>setTaskDraft({...taskDraft,notes:e.target.value})}/></label><label>任务成果链接<input type='url' placeholder='https://…；本地文件位置可写在记录里' value={taskDraft.resultUrl} onChange={e=>setTaskDraft({...taskDraft,resultUrl:e.target.value})}/></label>{editError&&<div className='form-error' role='alert'><p>{editError}</p><button type='button' className='button' onClick={()=>void recoverDraft('tasks')}>下载当前草稿并载入最新版本</button></div>}<div className='form-actions'><button type='button' className='button' onClick={()=>void copy(taskText(editedTask,taskDraft,states))}><Copy size={16}/>复制任务包</button><button className='button primary' type='submit'>{busy?'保存中…':'保存任务'}</button></div></fieldset></form></div></Modal>}
 {resource&&<Modal title={resource.name} subtitle={(resource.category||resource.kind)+' · 核查 '+(resource.checkedAt||'2026-09-23')} onClose={()=>setResource(null)}><div className='modal-body'><div className='evidence'>{resource.evidenceLevel||'官方文档核查；未试用'}</div><Field title='它解决什么'><Lines text={resource.summary}/></Field>{resource.workflow&&<Field title='产品实际工作方式'><Lines text={resource.workflow}/></Field>}<div className='reuse-box'><Field title='复用什么'><Lines text={resource.reuse}/></Field><Field title='如何复用'><Lines text={resource.reuseHow||resource.integration||'按官方技能说明准备输入，由现有 agent 执行；在任务卡保存结果。未验证的连接先手动试跑。'}/></Field><Field title='为什么值得'><Lines text={resource.reuseWhy||'复用现有方法或服务，减少重复搭建；先用一条真实内容验证是否节省操作和维护成本。'}/></Field></div>{resource.nontechnicalUse&&<Field title='非技术人员如何使用'><Lines text={resource.nontechnicalUse}/></Field>}<Field title='能力边界与限制'><Lines text={resource.limit}/></Field>{resource.approval&&<Field title='审查与批准'><Lines text={resource.approval}/></Field>}{resource.avoidBuilding&&<Field title='首版不要重复开发'><Lines text={resource.avoidBuilding}/></Field>}<Field title='接入与成本'><Lines text={[resource.availability,resource.effort,resource.pricing,resource.license].filter(Boolean).join('\n')}/></Field><Field title='原始来源'>{!resource.url&&!resource.sources?.length&&<p>原调研所用 Agent 环境的技能说明；新执行者需确认对应技能是否可用，本仓库未打包或接入该能力。</p>}<div className='source-list'>{(resource.sources?.length?resource.sources:[{label:'官方说明',url:resource.url}]).filter(s=>s.url).map((s,i)=><Source key={i} url={s.url}>{s.label}</Source>)}</div></Field></div></Modal>}
 {restore&&<Modal title='恢复本地备份' subtitle='恢复会替换模块、任务及新版备份中的内容项目；恢复前会自动保留快照。' busy={busy} onClose={()=>setRestore(null)}><div className='modal-body'><p>备份时间：{String(restore.exportedAt||'未知')}</p><p>包含 {restore.modules.length} 个模块、{restore.tasks.length} 条任务状态。{Array.isArray(restore.contentProjects)?'另含 '+restore.contentProjects.length+' 个内容项目，将替换当前内容及其历史版本。':'旧版备份不含内容项目，现有内容及历史版本会保留。'}素材文件不包含在此备份内。</p>{contentDirty&&<p className='form-error'>当前正文有未保存修改。确认恢复将放弃这些修改，请先取消并保存草稿。</p>}{editError&&<p role='alert' className='form-error'>{editError}</p>}<div className='form-actions'><button className='button' disabled={busy} onClick={()=>setRestore(null)}>取消</button><button className='button primary' disabled={busy} onClick={()=>void doRestore()}>{busy?'恢复中…':'确认恢复此备份'}</button></div></div></Modal>}
 </div>;
}
